In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pwd

'/Users/viveksasikumar/Downloads'

In [65]:
dataset = pd.read_csv('/Users/viveksasikumar/Downloads/Machine Learning A-Z/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Artificial_Neural_Networks/Churn_Modelling.csv')

In [66]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [67]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

# Data Preprocessing

In [68]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [69]:
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

In [70]:
X[1:10,:]

array([[608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]], dtype=object)

In [75]:
X[10:20,:]

array([[528, 0, 1, 31, 6, 102016.72, 2, 0, 0, 80181.12],
       [497, 2, 1, 24, 3, 0.0, 2, 1, 0, 76390.01],
       [476, 0, 0, 34, 10, 0.0, 2, 1, 0, 26260.98],
       [549, 0, 0, 25, 5, 0.0, 2, 0, 0, 190857.79],
       [635, 2, 0, 35, 7, 0.0, 2, 1, 1, 65951.65],
       [616, 1, 1, 45, 3, 143129.41, 2, 0, 1, 64327.26],
       [653, 1, 1, 58, 1, 132602.88, 1, 1, 0, 5097.67],
       [549, 2, 0, 24, 9, 0.0, 2, 1, 1, 14406.41],
       [587, 2, 1, 45, 6, 0.0, 1, 0, 0, 158684.81],
       [726, 0, 0, 24, 6, 0.0, 2, 1, 1, 54724.03]], dtype=object)

In [63]:
#onehotencoder = OneHotEncoder(categorical_features = [1])
#X = onehotencoder.fit_transform(X).toarray()

In [72]:
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [77]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/Users/viveksasikumar/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [107]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [108]:
classifier = Sequential()

In [114]:
#Input and 1st Hidden Layer 
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=10))

In [115]:
#adding 2nd Hidden Layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [116]:
#Output Layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [117]:
#Compiling ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [118]:
classifier.fit(X_train, y_train, batch_size=10, nb_epoch=100)

/Users/viveksasikumar/anaconda3/lib/python3.6/site-packages/keras/models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
6700/6700 [==============================] - 5s 714us/step - loss: 0.5953 - acc: 0.7913
Epoch 2/100
6700/6700 [==============================] - 4s 647us/step - loss: 0.5139 - acc: 0.7919
Epoch 3/100
6700/6700 [==============================] - 4s 646us/step - loss: 0.5115 - acc: 0.7919
Epoch 4/100
6700/6700 [==============================] - 4s 656us/step - loss: 0.5115 - acc: 0.7919
Epoch 5/100
6700/6700 [==============================] - 4s 652us/step - loss: 0.5115 - acc: 0.7919
Epoch 6/100
6700/6700 [==============================] - 4s 655us/step - loss: 0.5115 - acc: 0.7919
Epoch 7/100
6700/6700 [==============================] - 4s 658us/step - loss: 0.5115 - acc: 0.7919
Epoch 8/100
6700/6700 [==============================] - 4s 656us/step - loss: 0.5115 - acc: 0.7919
Epoch 9/100
6700/6700 [==============================] - 4s 663us/step - loss: 0.5115 - acc: 0.7919
Epoch 10/100
6700/6700 [==============================] - 4s 656us/step - loss: 0.5115 - acc: 0.7919

6700/6700 [==============================] - 4s 662us/step - loss: 0.5115 - acc: 0.7919
Epoch 83/100
6700/6700 [==============================] - 4s 651us/step - loss: 0.5115 - acc: 0.7919
Epoch 84/100
6700/6700 [==============================] - 4s 657us/step - loss: 0.5115 - acc: 0.7919
Epoch 85/100
6700/6700 [==============================] - 4s 659us/step - loss: 0.5115 - acc: 0.7919
Epoch 86/100
6700/6700 [==============================] - 4s 655us/step - loss: 0.5115 - acc: 0.7919
Epoch 87/100
6700/6700 [==============================] - 4s 655us/step - loss: 0.5116 - acc: 0.7919
Epoch 88/100
6700/6700 [==============================] - 4s 647us/step - loss: 0.5115 - acc: 0.7919
Epoch 89/100
6700/6700 [==============================] - 4s 650us/step - loss: 0.5116 - acc: 0.7919
Epoch 90/100
6700/6700 [==============================] - 4s 665us/step - loss: 0.5114 - acc: 0.7919
Epoch 91/100
6700/6700 [==============================] - 4s 652us/step - loss: 0.5115 - acc: 0.7919
Epo

In [119]:
y_pred = classifier.predict(X_test)

In [121]:
y_pred = (y_pred>0.5)

In [128]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [123]:
cm

array([[2657,    0],
       [ 643,    0]])

In [127]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.81      1.00      0.89      2657
          1       0.00      0.00      0.00       643

avg / total       0.65      0.81      0.72      3300



/Users/viveksasikumar/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [129]:
print(accuracy_score(y_test,y_pred))

0.805151515152
